flaskapp:
    image: test_docker:latest
    links:
     - mysql
    ports:
     - "8000:8000"
mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=dreamsteam_db
    volumes:
     - ~/Downloads/database:/var/lib/mysql
    ports:
      - "3306:3306"
